DROP TABLE IF EXISTS Nodes CASCADE;
DROP TABLE IF EXISTS Ways CASCADE;
DROP TABLE IF EXISTS Relations CASCADE;
DROP TABLE IF EXISTS Tags CASCADE;
DROP TABLE IF EXISTS Users CASCADE;

DROP TABLE IF EXISTS NodesInRelations CASCADE;
DROP TABLE IF EXISTS NodesInWays CASCADE;
DROP TABLE IF EXISTS WaysInRelations CASCADE;
DROP TABLE IF EXISTS NodeTags CASCADE;
DROP TABLE IF EXISTS WayTags CASCADE;
DROP TABLE IF EXISTS RelationTags CASCADE;

